# Site settings
title: Chowdown
email: lvdt88@gmail.com
description: The plain text recipe database for hackers
baseurl: ""
host: 0.0.0.0
language: "en"
lang_direction: "ltr"
color: "#ffaa00"
twitter_username: LvdT1988
github_username: LvdT

# Build settings
markdown: kramdown

permalink: /:title:output_ext

collections:
  components:
    output: true
  recipes:
    output: true

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

translation:
  en:
    components: "Components"
    ingredients: "Ingredients"
    directions: "Directions"
    tips: "Tips"
    category: "Category"
    nutritional_information: "Nutritional Information"
    component_based: 'This is a <strong class="blue">component-based recipe</strong>.'
    search: "Search"
    blog: "Blog"
    subscribe: "Subscribe"
